@ECHO OFF
ECHO BUILDING DEM CODE 4 WINDOWS LOL
ECHO REMEMBER DAT U NEED PYTHON ON DEM PATH LMAO
pip install pyinstaller
cd ..
mkdir compile
pyinstaller main.py --onefile -w --name CaveStoryDL --distpath compile
ECHO DONE BUILDING LMAO
ECHO REMEMBER TO PUT DA LOGO IN COMPILE FOLDER AND FROLIC YOOO
PAUSE
